package com.yaroslavm87.dogwalker.repository;

public enum RepoOperations {
    CREATE_SHELTER,
    READ_LIST_OF_SHELTERS,
    READ_LIST_OF_DOGS,
    READ_LIST_OF_WALKS_FOR_DOG,
    CREATE_DOG,
    UPDATE_DOG_DESCRIPTION,
    UPDATE_DOG_IMAGE,
    CREATE_RECORD_OF_DOG_WALK,
    DELETE_DOG,
    ADD_DOG_TO_LIST_OF_REMOVED_DOGS
}