package com.yaroslavm87.dogwalker.notifications;

public enum Event {
    REPO_NEW_DOG_OBJ_AVAILABLE,
    REPO_LIST_DOGS_ITEM_CHANGED,
    REPO_LIST_DOGS_ITEM_DELETED,
    REPO_NEW_WALK_RECORD_OBJ_AVAILABLE,
    REPO_LIST_WALK_RECORD_ITEM_DELETED,
    MODEL_LIST_DOGS_ITEM_ADDED,
    MODEL_LIST_DOGS_ITEM_CHANGED,
    MODEL_LIST_DOGS_ITEM_DELETED,
    DOG_IMAGE_RES_ID_CHANGED,
    MODEL_LIST_WALK_RECORDS_ITEM_ADDED,
    MODEL_MESSAGE
}
