package com.yaroslavm87.dogwalker.notifications;

public enum Event {
    REPO_LIST_DOGS_CHANGED,
    REPO_LIST_DOGS_ITEM_ADDED,
    REPO_LIST_DOGS_ITEM_DELETED,
    MODEL_LIST_DOGS_CHANGED,
    MODEL_LIST_DOGS_ITEM_ADDED,
    MODEL_LIST_DOGS_ITEM_DELETED,
    DOG_NAME_CHANGED,
    DOG_IMAGE_RES_ID_CHANGED
}
